### PR TITLE
fix: use of headful parameter

### LINKED ISSUE #219: Headful mode is not showing the browser
Headful mode is not displaying the browsers in version 0.191.0. (Note: It was working in version 0.171.0).

The command I am using is: `npx folio --param headful`

### PR DESCRIPTION
**Pull request by mxschmitt**
fixes #219

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -83,17 +83,21 @@ type PlaywrightTestFixtures = {
...
-fixtures.headful.initParameter('Whether to run tests headless or headful', process.env.HEADFUL ? true : undefined);
+fixtures.headful.initParameter('Whether to run tests headless or headful', process.env.HEADFUL ? true : false);
 fixtures.platform.initParameter('Operating system', process.platform as ('win32' | 'linux' | 'darwin'));
 fixtures.screenshotOnFailure.initParameter('Generate screenshot on failure', false);
 fixtures.slowMo.initParameter('Slows down Playwright operations by the specified amount of milliseconds', 0);
 fixtures.video.initParameter('Record videos while running tests', false);
 
 fixtures.browserOptions.init(async ({ headful, slowMo }, run) => {
+  let headless;
+  if (!process.env.PWDEBUG && typeof headful !== 'undefined')
```
Comment (dgozman) [inline src/index.ts:94]: Why do we need this? When I try locally with just `headless:  !headful`, everything works as expected with PWDEBUG=1.

Comment (mxschmitt) [reply src/index.ts]: My bad, I should have added some context so its easier understandable. In #212 a change was merged that if no headful parameter is specified, `undefined` gets passed for the `headless` option. This fixed the case, that `PWDEBUG` was not working when `headless: false` got passed to Playwright - which sounded like an upstream bug.

I tried to revert the previous change since PW should handle that and it seems to still work fine with the test cases below which all result in a headful instance are passing:

- `PWDEBUG=1 npx folio -j 1 --retries 3 --reporter list try-playwright.spec.ts`
- `HEADFUL=1 npx folio -j 1 --retries 3 --reporter list try-playwright.spec.ts`
- `npx folio -j 1 --retries 3 --reporter list try-playwright.spec.ts --param headful`

So I changed my PR to just revert the previous change.

Comment (dgozman) [reply src/index.ts]: Great, thank you for more details!

**Review by dgozman — APPROVED** [review]

File: src/index.ts (hunk 1 above)
Comment (nrhoffmann) [reply src/index.ts]: _Arguably_ this is an upstream bug. From playwright's perspective, why environment variables override explicit configuration?

Comment (mxschmitt) [reply src/index.ts]: You mean PWDEBUG? Maybe there was a case which I miss but in my mind its expected when the user uses PWDEBUG that its headfull always.

Comment (nrhoffmann) [reply src/index.ts]: Fair. That is actually quite reasonable.
